/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TopUpOrderInput = IDL.Record({
  'playerUID' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'diamondAmount' : IDL.Nat,
  'priceNPR' : IDL.Nat,
});
export const TopUpOrder = IDL.Record({
  'playerUID' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'diamondAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'priceNPR' : IDL.Nat,
});
export const ApiConfig = IDL.Record({
  'provider' : IDL.Text,
  'isConfigured' : IDL.Bool,
});
export const ManualOrder = IDL.Record({
  'id' : IDL.Text,
  'playerUID' : IDL.Text,
  'packageName' : IDL.Text,
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
  'priceNPR' : IDL.Nat,
  'screenshotData' : IDL.Text,
});
export const TopUpRecord = IDL.Record({
  'id' : IDL.Text,
  'uid' : IDL.Text,
  'packageName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'amount' : IDL.Nat,
  'packageId' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const TopUpRequest = IDL.Record({
  'uid' : IDL.Text,
  'packageName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'amount' : IDL.Nat,
  'packageId' : IDL.Text,
});
export const TopUpResult = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  'createTopUpOrder' : IDL.Func([TopUpOrderInput], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(TopUpOrder)], ['query']),
  'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
  'getManualOrders' : IDL.Func([], [IDL.Vec(ManualOrder)], ['query']),
  'getTopUpHistory' : IDL.Func([], [IDL.Vec(TopUpRecord)], ['query']),
  'markOrderCompleted' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'processTopUp' : IDL.Func([TopUpRequest], [TopUpResult], []),
  'setApiConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitManualOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TopUpOrderInput = IDL.Record({
    'playerUID' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'diamondAmount' : IDL.Nat,
    'priceNPR' : IDL.Nat,
  });
  const TopUpOrder = IDL.Record({
    'playerUID' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'diamondAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'priceNPR' : IDL.Nat,
  });
  const ApiConfig = IDL.Record({
    'provider' : IDL.Text,
    'isConfigured' : IDL.Bool,
  });
  const ManualOrder = IDL.Record({
    'id' : IDL.Text,
    'playerUID' : IDL.Text,
    'packageName' : IDL.Text,
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
    'priceNPR' : IDL.Nat,
    'screenshotData' : IDL.Text,
  });
  const TopUpRecord = IDL.Record({
    'id' : IDL.Text,
    'uid' : IDL.Text,
    'packageName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'amount' : IDL.Nat,
    'packageId' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const TopUpRequest = IDL.Record({
    'uid' : IDL.Text,
    'packageName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'amount' : IDL.Nat,
    'packageId' : IDL.Text,
  });
  const TopUpResult = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    'createTopUpOrder' : IDL.Func([TopUpOrderInput], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(TopUpOrder)], ['query']),
    'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
    'getManualOrders' : IDL.Func([], [IDL.Vec(ManualOrder)], ['query']),
    'getTopUpHistory' : IDL.Func([], [IDL.Vec(TopUpRecord)], ['query']),
    'markOrderCompleted' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'processTopUp' : IDL.Func([TopUpRequest], [TopUpResult], []),
    'setApiConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitManualOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };