/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiConfig { 'provider' : string, 'isConfigured' : boolean }
export interface ManualOrder {
  'id' : string,
  'playerUID' : string,
  'packageName' : string,
  'status' : string,
  'timestamp' : bigint,
  'priceNPR' : bigint,
  'screenshotData' : string,
}
export interface TopUpOrder {
  'playerUID' : string,
  'paymentMethod' : string,
  'diamondAmount' : bigint,
  'timestamp' : bigint,
  'priceNPR' : bigint,
}
export interface TopUpOrderInput {
  'playerUID' : string,
  'paymentMethod' : string,
  'diamondAmount' : bigint,
  'priceNPR' : bigint,
}
export interface TopUpRecord {
  'id' : string,
  'uid' : string,
  'packageName' : string,
  'paymentMethod' : string,
  'message' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'amount' : bigint,
  'packageId' : string,
  'transactionId' : string,
}
export interface TopUpRequest {
  'uid' : string,
  'packageName' : string,
  'paymentMethod' : string,
  'amount' : bigint,
  'packageId' : string,
}
export interface TopUpResult {
  'message' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'transactionId' : string,
}
export interface _SERVICE {
  'createTopUpOrder' : ActorMethod<[TopUpOrderInput], undefined>,
  'getAllOrders' : ActorMethod<[], Array<TopUpOrder>>,
  'getApiConfig' : ActorMethod<[], ApiConfig>,
  'getManualOrders' : ActorMethod<[], Array<ManualOrder>>,
  'getTopUpHistory' : ActorMethod<[], Array<TopUpRecord>>,
  'markOrderCompleted' : ActorMethod<[string], boolean>,
  'processTopUp' : ActorMethod<[TopUpRequest], TopUpResult>,
  'setApiConfig' : ActorMethod<[string, string, string], undefined>,
  'submitManualOrder' : ActorMethod<[string, string, bigint, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];