/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TopUpResult {
    message: string;
    timestamp: bigint;
    success: boolean;
    transactionId: string;
}
export interface TopUpRecord {
    id: string;
    uid: string;
    packageName: string;
    paymentMethod: string;
    message: string;
    timestamp: bigint;
    success: boolean;
    amount: bigint;
    packageId: string;
    transactionId: string;
}
export interface ManualOrder {
    id: string;
    playerUID: string;
    packageName: string;
    status: string;
    timestamp: bigint;
    priceNPR: bigint;
    screenshotData: string;
}
export interface ApiConfig {
    provider: string;
    isConfigured: boolean;
}
export interface TopUpRequest {
    uid: string;
    packageName: string;
    paymentMethod: string;
    amount: bigint;
    packageId: string;
}
export interface TopUpOrderInput {
    playerUID: string;
    paymentMethod: string;
    diamondAmount: bigint;
    priceNPR: bigint;
}
export interface TopUpOrder {
    playerUID: string;
    paymentMethod: string;
    diamondAmount: bigint;
    timestamp: bigint;
    priceNPR: bigint;
}
export interface backendInterface {
    createTopUpOrder(orderInput: TopUpOrderInput): Promise<void>;
    getAllOrders(): Promise<Array<TopUpOrder>>;
    getApiConfig(): Promise<ApiConfig>;
    getManualOrders(): Promise<Array<ManualOrder>>;
    getTopUpHistory(): Promise<Array<TopUpRecord>>;
    markOrderCompleted(orderId: string): Promise<boolean>;
    processTopUp(request: TopUpRequest): Promise<TopUpResult>;
    setApiConfig(key: string, baseUrl: string, provider: string): Promise<void>;
    submitManualOrder(playerUID: string, packageName: string, priceNPR: bigint, screenshotData: string): Promise<string>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTopUpOrder(arg0: TopUpOrderInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTopUpOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTopUpOrder(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<TopUpOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getApiConfig(): Promise<ApiConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiConfig();
            return result;
        }
    }
    async getManualOrders(): Promise<Array<ManualOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualOrders();
            return result;
        }
    }
    async getTopUpHistory(): Promise<Array<TopUpRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUpHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUpHistory();
            return result;
        }
    }
    async markOrderCompleted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderCompleted(arg0);
            return result;
        }
    }
    async processTopUp(arg0: TopUpRequest): Promise<TopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processTopUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processTopUp(arg0);
            return result;
        }
    }
    async setApiConfig(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async submitManualOrder(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitManualOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitManualOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
